# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sattendance.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3,sys
import time
import datetime
import os,csv
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_at(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.setEnabled(True)
        main.resize(600, 601)
        font = QtGui.QFont()
        font.setKerning(True)
        main.setFont(font)
        main.setStyleSheet("")
        main.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 600, 601))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("background/minimalist-4k-wallpaper-hd-15-920x518.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.attendframe = QtWidgets.QFrame(self.centralwidget)
        self.attendframe.setGeometry(QtCore.QRect(10, 20, 581, 571))
        self.attendframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.attendframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.attendframe.setObjectName("attendframe")
        self.label = QtWidgets.QLabel(self.attendframe)
        self.label.setGeometry(QtCore.QRect(0, 0, 581, 571))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("background/HD-wallpaper-portrait-display-vertical-pattern-digital-art-cyan-polygon-art.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.attendframe)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 181, 61))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.attendframe)
        self.tableWidget.setGeometry(QtCore.QRect(10, 90, 561, 471))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setStyleSheet("font: 12pt \"Sitka\";\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        
        self.viewrec()
        
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.loginlogo = QtWidgets.QLabel(self.attendframe)
        self.loginlogo.setGeometry(QtCore.QRect(150, 10, 71, 71))
        self.loginlogo.setAutoFillBackground(False)
        self.loginlogo.setText("")
        self.loginlogo.setPixmap(QtGui.QPixmap("background/nemco_logo1.jpg"))
        self.loginlogo.setScaledContents(True)
        self.loginlogo.setWordWrap(False)
        self.loginlogo.setObjectName("loginlogo")
        main.setCentralWidget(self.centralwidget)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Student Attendance"))
        self.label_2.setText(_translate("main", "ATTENDANCE"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("main", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("main", "Student ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("main", "Vaccine Status"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("main", "Date"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("main", "Time"))
        
         
    def viewrec(self):
        #self.view_reg()
        self.add_registerattend()
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.resizeColumnsToContents()
#         self.add_registerattend()

    def view_reg(self):
        conn = self.connectionattend()
        cur = conn.cursor()
        data = cur.execute("select * from Attendance")

        row = 0
        self.tableWidget.setRowCount(row)
        for row_count, row_data in enumerate(data):
            self.tableWidget.insertRow(row_count)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_count, column_number,QTableWidgetItem(str(data)))
    
    def add_registerattend(self):
                conn = self.connectionattend()
                cur = conn.cursor()
                
                cur.execute("CREATE TABLE IF NOT EXISTS Attendance (Name TEXT NOT NULL, ID INTEGER NOT NULL, Vaccine_Status TEXT NOT NULL, Date TEXT NOT NULL, Time TEXT NOT NULL)")
#                 self.newattendance()
                self.newattendance()
                conn.commit()
                conn.close()
                self.view_reg()
    
        
        
        
    def newattendance(self):
        connection = self.connectionattend()
        cursor = connection.cursor()
        
#         self.add_registerattend()
        ts = time.time()
        date = datetime.datetime.fromtimestamp(ts).strftime('%d-%m-%Y')
        with open("/home/admin/Desktop/Thesis/Attendance/Attendance_" + date + ".csv", 'r') as file:
            no_records = 0
            for row in file:
                cursor.execute("INSERT INTO Attendance VALUES (?,?,?,?,?)",row.split(","))

                connection.commit()
                no_records +=1
        connection.close()
        
        print('\n{} Records Transferred'.format(no_records))
    
    def connectionattend(self):
        try:
            conn = sqlite3.connect("attendance.db")
        except:
            print("cannot connect to the database")
        return conn
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QMainWindow()
    ui = Ui_at()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
