# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Super_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from create_acc import Ui_Formcreate



class Ui_Formsuper(object):
    def setupUi(self, Formsu):
        Formsu.setObjectName("Form")
        Formsu.resize(463, 531)
        self.admintext = QtWidgets.QLabel(Formsu)
        self.admintext.setGeometry(QtCore.QRect(180, 190, 81, 81))
        #self.center()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.admintext.setFont(font)
        self.admintext.setAutoFillBackground(False)
        self.admintext.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.admintext.setObjectName("admintext")
        self.username = QtWidgets.QLineEdit(Formsu)
        self.username.setGeometry(QtCore.QRect(60, 260, 321, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.username.setFont(font)
        self.username.setStyleSheet("border-radius: 10px")
        self.username.setObjectName("username")
        self.loginlogo = QtWidgets.QLabel(Formsu)
        self.loginlogo.setGeometry(QtCore.QRect(150, 60, 141, 121))
        self.loginlogo.setAutoFillBackground(False)
        self.loginlogo.setText("")
        self.loginlogo.setPixmap(QtGui.QPixmap("background/nemco_logo1.jpg"))
        self.loginlogo.setScaledContents(True)
        self.loginlogo.setWordWrap(False)
        self.loginlogo.setObjectName("loginlogo")
        self.password = QtWidgets.QLineEdit(Formsu)
        self.password.setGeometry(QtCore.QRect(60, 300, 321, 31))
        font = QtGui.QFont()
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        font.setItalic(True)
        self.password.setFont(font)
        self.password.setStyleSheet("border-radius: 10px")
        self.password.setObjectName("password")
        self.background = QtWidgets.QLabel(Formsu)
        self.background.setGeometry(QtCore.QRect(0, 0, 463, 531))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("background/minimalist-4k-wallpaper-hd-15-920x518.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.login = QtWidgets.QPushButton(Formsu)
        self.login.setGeometry(QtCore.QRect(180, 350, 75, 31))
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login.setAutoFillBackground(False)
        self.login.setStyleSheet("font: 12pt \"Sitka\";\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.login.setDefault(False)
        self.login.setObjectName("login")

        self.login.clicked.connect(self.createbutton)

        self.background.raise_()
        self.admintext.raise_()
        self.username.raise_()
        self.loginlogo.raise_()
        self.password.raise_()
        self.login.raise_()

        self.retranslateUi(Formsu)
        QtCore.QMetaObject.connectSlotsByName(Formsu)

    def retranslateUi(self, Formsu):
        _translate = QtCore.QCoreApplication.translate
        Formsu.setWindowTitle(_translate("Form", "Form"))
        self.admintext.setText(_translate("Form", "Admin"))
        self.username.setPlaceholderText(_translate("Form", "Username"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.login.setText(_translate("Form", "Login"))
    
    def createbutton(self):
        self.out()
        self.delete()
        #print("hello")
        #Formsu.close()

    def createwindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Formcreate()
        self.ui.setupUi(self.window)
        self.window.show()

    def warn(self):
        msg = QMessageBox()
        msg.setWindowTitle("Notice")
        msg.setText("CONTACT THE ADMIN")
        x = msg.exec()
        
    def out(self):
        usernames = self.username.text()
        passwords = self.password.text()

        if len(usernames)== 0 or len(passwords)==0:
            msg = QMessageBox()
            msg.setWindowTitle("WARNING")
            msg.setText("MUST INPUT TEXT")
            x = msg.exec()
            
        elif usernames == "default" and passwords == "default":
            self.loginw()
        else:

            conn = self.connecting()
            cur = conn.cursor()

            user = 'SELECT ID_Number FROM Admin WHERE ID_Number = \'' + usernames + "\'"
            if cur.execute(user):
                for x in cur.execute(user):
                    self.passwords()
                    #print(x)

    def passwords(self):
        passwords = self.password.text()

        conn = self.connecting()
        cur = conn.cursor()

        pas = 'SELECT Password FROM admin WHERE Password = \'' + passwords + "\'"

        if cur.execute(pas):
            for y in cur.execute(pas):
                #print(y)
                self.loginw()

    def connecting(self):
        try:
            conn = sqlite3.connect("admin.db")
        except:
            print("cannot connect to the database")
        return conn

    def loginw(self):
        msg = QMessageBox()
        msg.setWindowTitle("LOGIN")
        msg.setText("LOGIN")
        x = msg.exec()

        self.createwindow()

    
    def warn(self):
        msg = QMessageBox()
        msg.setWindowTitle("WARNING")
        msg.setText("INCORRECT USERNAME/PASSWORD")
        x = msg.exec()
        
    def delete(self):
        self.username.clear()
        self.password.clear()
        
    
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Formsu = QtWidgets.QWidget()
    ui = Ui_Formsuper()
    ui.setupUi(Formsu)
    Formsu.show()
    sys.exit(app.exec_())
